#!/bin/sh
#
#   Copyright 2012 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

source envcov.sh

"${LCOV_PATH}/lcov" -d "${OBJ_DIR}" --zerocounters
