#!/bin/sh
#   XcodeCoverage by Jon Reid, http://qualitycoding/about/
#   Copyright 2014 Jonathan M. Reid. See LICENSE.txt

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/envcov.sh

remove_old_report()
{
    pushd "${BUILT_PRODUCTS_DIR}"
    if [ -e lcov ]; then
        rm -r lcov
    fi
    popd
}

enter_lcov_dir()
{
    cd "${BUILT_PRODUCTS_DIR}"
    mkdir lcov
    cd lcov
}

gather_coverage()
{
    LCOV --capture --derive-func-data -b "${SRCROOT}" -d "${OBJ_DIR}" -o ${LCOV_INFO}
}

exclude_data()
{
    LCOV --remove ${LCOV_INFO} "Developer/SDKs/*" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    LCOV --remove ${LCOV_INFO} "main.m" -d "${OBJ_DIR}" -o ${LCOV_INFO}
    # Remove other patterns here...
}

generate_report()
{
    "${LCOV_PATH}/genhtml" --output-directory . ${LCOV_INFO}
    open index.html
}

remove_old_report
enter_lcov_dir
gather_coverage
exclude_data
generate_report
